package eu.zeigermann.vaadin.demo.forms.autobind;

import com.vaadin.data.fieldgroup.BeanFieldGroup;
import com.vaadin.data.fieldgroup.FieldGroup;
import com.vaadin.data.util.BeanItem;
import com.vaadin.server.VaadinRequest;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;

public class AutoGeneratedFormUI extends UI {
	@Override
	public void init(VaadinRequest request) {
		VerticalLayout layout = new VerticalLayout();
		setContent(layout);
		FieldGroup fieldGroup = new BeanFieldGroup<Person>(Person.class);

		// We need an item data source before we create the fields to be able to
		// find the properties, otherwise we have to specify them by hand
		fieldGroup.setItemDataSource(new BeanItem<Person>(new Person("John",
				"Doe", 34)));

		// Loop through the properties, build fields for them and add the fields
		// to this UI
		for (Object propertyId : fieldGroup.getUnboundPropertyIds()) {
			layout.addComponent(fieldGroup.buildAndBind(propertyId));
		}
	}
}